### ISSUE TITLE
Provide a ready-to-start (alternate ?) `docker-compose.yml` file with `lookupd` inside

### ISSUE THREAD

**Issue by moul** [icecrime/vossibility-stack#1]
So it is easier to test it without need to find out how to setup a nsqd server :)

**Comment by icecrime** [comment]
Agreed, the `docker-compose.yml` is super incomplete right now and relies on pieces of infrastructure I already had in place ;-) Still haven't had time to work through this though.

**Comment by icecrime** [comment]
Closed by #3.

**Comment by moul** [comment]
:+1:
