### ISSUE TITLE
Kibana can't connect to elastic search

### ISSUE THREAD

**Issue by AutomatedTester** [icecrime/vossibility-stack#2]
I have just pulled everything and done `docker-compose up` and it downloaded it got started but kibana doesnt appear to see the ES server.

```
kibana_1        | {"name":"Kibana","hostname":"3e00e2fb57f2","pid":1,"level":40,"msg":"No living connections","time":"2015-10-15T20:55:56.445Z","v":0}
kibana_1        | {"name":"Kibana","hostname":"3e00e2fb57f2","pid":1,"level":30,"msg":"Unable to connect to elasticsearch at http://localhost:9200. Retrying in 2.5 seconds.","time":"2015-10-15T20:55:56.445Z","v":0}

```

I can't see that I missed a step but if you can help that would be great.

**Comment by icecrime** [comment]
I have seen the case on a very small machine where ElasticSearch was taking so much resources that Kibana was failing to connect in time. Otherwise I'm sorry, I don't have a better idea here :-/
